[package]
name = "axum-starter"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["./codegen/derive_starter"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
axum = "0.5.16"
derive-starter = { version = "0.1.0", path = "codegen/derive_starter" }
futures = "0.3.24"
http-body = "0.4.5"
hyper = { version = "0.14.20", features = ["server"] }
tap = "1.0.1"
thiserror = "1.0.37"
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["catch-panic"] }

[dev-dependencies]
tokio = { version = "1.21.2", features = ["full"] }
