[package]
name = "axum-starter"
version = "0.1.0"
edition = "2021"
authors = ["FrozenString<frozenstringstable@gmail.com>"]
description = "A help crate for simplify the code of starting axum server "
homepage = "https://github.com/Goodjooy/axum-server-starter"
documentation = "https://docs.rs/axum-starter"
license = "MIT"
keywords = ["web", "http", "axum"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace]
members = ["./codegen/axum-starter-macro", "./examples/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
axum = "0.5.16"
axum-starter-macro = { version = "0.1.0", path = "codegen/axum-starter-macro" }
futures = "0.3.24"
http-body = "0.4.5"
hyper = { version = "0.14.20", features = ["server"] }
log = "0.4.17"
tap = "1.0.1"
thiserror = "1.0.37"
tower = "0.4.13"

[dev-dependencies]
tower-http = { version = "0.3.4", features = ["catch-panic", "trace"] }
tokio = { version = "1.21.2", features = ["full"] }
simple_logger = "2.3.0"
