name: check CI

on:
  pull_request:
    branches: [master, next]
    paths-ignore:
      - "**.md"

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          default: true
      - run: cargo fmt --check
      - run: cargo clippy --no-default-features
      - run: cargo clippy --all-features
